### PR TITLE
Add SASL EXTERNAL option

### PR DESCRIPTION
**Pull request by grs**

### CODE REVIEW

**Comment by grs** [comment]
Anyone able to review this?

**Comment by HolyKau** [comment]
Hi, would you be able to provide an example that utilizes the SASL EXTERNAL option?

**Comment by willowglensystems** [comment]
> Hi, would you be able to provide an example that utilizes the SASL EXTERNAL option?

It looks like I was just missing a change in the types.go to not omit the InitialResponse

```
func (si *saslInit) marshal(wr *buffer) error {
	return marshalComposite(wr, typeCodeSASLInit, []marshalField{
		{value: &si.Mechanism, omit: false},
		{value: &si.InitialResponse, omit: false},
		{value: &si.Hostname, omit: len(si.Hostname) == 0},
	})
}
```

With that implemented I was able to get this working with the following code
```
        roots := x509.NewCertPool()
        data, err := ioutil.ReadFile("ca.crt")

        if err != nil {
                fmt.Errorf("Error reading in root CA: %s", err)
                return
        }

        roots.AppendCertsFromPEM(data)
        cert, err := tls.LoadX509KeyPair("tls.crt", "tls.key")

        if err != nil {
                fmt.Errorf("Error loading certificate: %s", err)
                return
        }

        // Create client
        client, err := amqp.Dial("amqps://rabbitmq",
                amqp.ConnSASLExternal(),
                amqp.ConnTLSConfig(&tls.Config {
                        Certificates: []tls.Certificate{cert},
                        RootCAs: roots,
                        InsecureSkipVerify: false,
                }),
        )
```

**Comment by HolyKau** [comment]
> Hi, would you be able to provide an example that utilizes the SASL EXTERNAL option?

It looks like I was just missing a change in the types.go to not omit the InitialResponse

```
func (si *saslInit) marshal(wr *buffer) error {
	return marshalComposite(wr, typeCodeSASLInit, []marshalField{
		{value: &si.Mechanism, omit: false},
		{value: &si.InitialResponse, omit: false},
		{value: &si.Hostname, omit: len(si.Hostname) == 0},
	})
}
```

With that implemented I was able to get this working with the following code
```
        roots := x509.NewCertPool()
        data, err := ioutil.ReadFile("ca.crt")

        if err != nil {
                fmt.Errorf("Error reading in root CA: %s", err)
                return
        }

        roots.AppendCertsFromPEM(data)
        cert, err := tls.LoadX509KeyPair("tls.crt", "tls.key")

        if err != nil {
                fmt.Errorf("Error loading certificate: %s", err)
                return
        }

        // Create client
        client, err := amqp.Dial("amqps://rabbitmq",
                amqp.ConnSASLExternal(),
                amqp.ConnTLSConfig(&tls.Config {
                        Certificates: []tls.Certificate{cert},
                        RootCAs: roots,
                        InsecureSkipVerify: false,
                }),
        )
```

**Pull request closed without merging**
