### PR TITLE
Expose retrieval of link source filter values

### PR DESCRIPTION
**Pull request by jhendrixMSFT**

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
With this change I was able to fix the `nil` session ID issue we've been talking about.

The API conforms to [`LinkSourceFilter()`](https://github.com/Azure/go-amqp/blob/master/client.go#L468) which is why it returns an `interface{}`.

My only question is if it's ok to just blindly copy the filters in the response.

**Comment by richardpark-msft** [comment]
> With this change I was able to fix the `nil` session ID issue in SB we've been talking about.
> 
> The API conforms to [`LinkSourceFilter()`](https://github.com/Azure/go-amqp/blob/master/client.go#L468) which is why it returns an `interface{}`.
> 
> My only question is if it's ok to just blindly copy the filters in the response. Do you know how this works in the JS implementation, or where I should dig around in their code?

You should be able to. The JS code does a check to see if the '_providedSessionId' === 'receivedSessionId', even when the user specifies one.

You can see that check here: [link](https://github.com/Azure/azure-sdk-for-js/blob/281b17ed42e29012be7089ae6f57a75e08633f62/sdk/servicebus/service-bus/src/session/messageSession.ts#L275)

**Comment by jhendrixMSFT** [comment]
That part I get.  What I'm wondering about is how this change copies the received filter map over what was created.

On line 80, the call to `newLink()` creates a link/source and will populate `l.source.Filter` with any filters provided by the caller (by way of the `opts` param).

In this change, after the connection has been established, we take the contents of the received filters (which contains the session ID) and copy them into the link that we hand back to the caller.  A few lines above you can see we do something similar with `Source.Address`.

It _looks_ like they do something similar in the .NET [implementation](https://github.com/Azure/azure-amqp/blob/master/src/AmqpLink.cs#L1053).  Was hoping for a more definitive answer.

**Comment by UnwashedMeme** [comment]
With this and the paired changes in azure-service-bus-go it works in my test playground. :grin:

**Comment by jhendrixMSFT** [comment]
@serbrech do you have any thoughts on this?

**Comment by serbrech** [comment]
Not really, I havent looked into what the link filter is in amqp.

**Comment by jhendrixMSFT** [comment]
Based on the spec I believe that copying the received filters is the correct action.

> The receiving endpoint sets its desired filter, the sending endpoint sets the filter actually in place (including any filters defaulted at the node). The receiving endpoint MUST check that the filter in place meets its needs and take responsibility for detaching if it does not.

So we, the receiving endpoint, set our desired filter of `nil` `session-filter` and the sending endpoint (Azure SB) returns the filter that actually gets used (any available session).  We then take that result and copy it into the link we expose to clients.

**Review by richardpark-msft — APPROVED** [review]
Looks sensible to me, sorry for taking so long on the review!

**Pull request merged**
